---
title: "FTICR"
output: 
  github_document:
  html_preview: true
date: "2023-05-02"
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE
                      )
```
## FT-MS (FT-ICR)

<details>
  <summary>click to open</summary>

### FTICR  Van krevalin diagrams:

<details>
  <summary>click to open</summary>
  
```{r , fig.height=9, fig.width=9}
ggExtra::ggMarginal(gg_FTICR_vk$gg_vk_polar_nonpolar, groupColour = TRUE, groupFill = TRUE, alpha = 0.1)

```

```{r , fig.height=9, fig.width=9}
tar_read(gg_FTICR_vk)$gg_vk_domains
tar_read(gg_FTICR_vk)$gg_vk_all
tar_read(gg_FTICR_vk)$gg_vk_all_pre
```
</details>

### FTICR  Common vs unique peaks by treatment:

<details>
  <summary>click to open</summary>

<details>
  <summary>click to open</summary>

```{r , fig.height=6, fig.width=6}
tar_read(gg_FTICR_unique)$gg_unique_pre
tar_read(gg_FTICR_unique)$gg_common_unique
tar_read(gg_FTICR_unique)$fticr_unique_summary
  tar_read(gg_FTICR_unique)$gg_common_unique_inc
  tar_read(gg_FTICR_unique)$fticr_unique_summary_inc
  tar_read(gg_FTICR_unique)$gg_common_unique_inc_pre
  tar_read(gg_FTICR_unique)$fticr_unique_summary_inc_pre
  
```
</details>

<details>
  <summary>click to open</summary>

```{r , fig.height=6, fig.width=6}
tar_read(gg_FTICR_unique_polar)$gg_unique_pre
tar_read(gg_FTICR_unique_polar)$gg_common_unique
tar_read(gg_FTICR_unique_polar)$fticr_unique_summary
  tar_read(gg_FTICR_unique_polar)$gg_common_unique_inc
  tar_read(gg_FTICR_unique_polar)$fticr_unique_summary_inc
  tar_read(gg_FTICR_unique_polar)$gg_common_unique_inc_pre
  tar_read(gg_FTICR_unique_polar)$fticr_unique_summary_inc_pre
  
```
</details>

<details>
  <summary>click to open</summary>

```{r , fig.height=6, fig.width=6}
tar_read(gg_FTICR_unique_nonpolar)$gg_unique_pre
tar_read(gg_FTICR_unique_nonpolar)$gg_common_unique
tar_read(gg_FTICR_unique_nonpolar)$fticr_unique_summary
  tar_read(gg_FTICR_unique_nonpolar)$gg_common_unique_inc
  tar_read(gg_FTICR_unique_nonpolar)$fticr_unique_summary_inc
  tar_read(gg_FTICR_unique_nonpolar)$gg_common_unique_inc_pre
  tar_read(gg_FTICR_unique_nonpolar)$fticr_unique_summary_inc_pre
  
```
</details>

</details>

### FTICR  Permanova results and PCAs:

#### relative abundance
<details>
  <summary>click to open</summary>

```{r , fig.height=6, fig.width=6}
tar_read(gg_FTICR_relabund)$relabund
tar_read(gg_FTICR_relabund)$relabund_p
tar_read(gg_FTICR_relabund)$relabund_np
```


#### PCA results:
<details>
  <summary>click to open</summary>


```{r , fig.height=6, fig.width=6}
tar_read(gg_FTICR_PCA)$gg_pca_polar_nonpolar
tar_read(gg_FTICR_PCA)$gg_pca_polar_nonpolar_pre
tar_read(gg_FTICR_PCA)$gg_pca_polar_nonpolar_inc
tar_read(gg_FTICR_permanova)$permanova_fticr_all

  tar_read(gg_FTICR_PCA)$gg_pca_by_pre_polar
   tar_read(gg_FTICR_PCA)$gg_pca_by_inc_polar
   tar_read(gg_FTICR_permanova)$permanova_fticr_polar
   
  tar_read(gg_FTICR_PCA)$gg_pca_by_pre_nonpolar
  tar_read(gg_FTICR_PCA)$gg_pca_by_inc_nonpolar
  tar_read(gg_FTICR_permanova)$permanova_fticr_nonpolar
```
</details>

</details>


</details>

## Session Info 

<details>
  <summary> Session Info </summary>

Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>