---
title: "GC_LC_Lipids"
output: 
  github_document:
  html_preview: true
date: "2023-04-25"
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE
                      )
```

## GC

<details>
  <summary>click to open</summary>


```{r , fig.height=15, fig.width=20}
tar_read(gg_GC)
```


#### PCA
<details>
  <summary>click to open</summary>


```{r , fig.height=15, fig.width=20}
tar_read(gg_GC_PCA)
```

</details>



</details>
## LC

<details>
  <summary>click to open</summary>
 

```{r , fig.height=15, fig.width=20}
tar_read(gg_LC)
```
#### PCA
<details>
  <summary>click to open</summary>


```{r , fig.height=15, fig.width=20}
tar_read(gg_LC_PCA)
```

</details>




</details>

## Lipids

<details>
  <summary>click to open</summary>
 

```{r , fig.height=6, fig.width=9}

tar_read(gg_Lipid)

```

</details>


## Session Info 

<details>
  <summary> Session Info </summary>

Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>